function [surfaces, surfacequalities, surfacenames] = CleanRawSurfaceData(rawsurfaces)
%function [cleansurfaces, surfacenames] = CleanRawSurfaceData(rawsurfaces)
%  DESCRIPTION
%    This function is used to remove outliers in the data set.
%    It will also remove invalid data (NaN) and empty surface data.
%  INPUT
%    rawsurfaces: A N x 2 matrix of surface data imported from N files generated by MAEVA.
%  OUTPUT
%    surfaces: An array of N cleaned surface data.
%    surfacequalities: An array of N ratios representing the quality of the
%                      raw data before removing the NaNs.
%                      quality = 1 - (overruns * ADXL345 buffer size / data size)
%    surfacenames: An array of N surface names.

    BUFFERSIZE = 32;

    surfaceindex = 1;
    for surface = 1 : size(rawsurfaces, 1)
        if (~isempty(rawsurfaces{surface}))

            [~, remainder] = strtok(rawsurfaces{surface, 1}{7});
            surfacequalities{surfaceindex} = (1.0 - (str2double(strtrim(remainder)) * BUFFERSIZE / size(rawsurfaces{surface, 2}, 1))) * 100.0;

            [~, remainder] = strtok(rawsurfaces{surface, 1}{2});
            surfacenames{surfaceindex} = strtrim(remainder);

            disp(['Cleaning data for surface ', num2str(surface)]);
            disp(['   Quality: ', num2str(surfacequalities{surfaceindex}, '%.2f')]);
            disp(['   Name: ', surfacenames{surfaceindex}]);
            surfaces{surfaceindex} = RemoveOutliers(rawsurfaces{surface, 2});

            surfaceindex = surfaceindex + 1;
        end
    end
end
