function [features, featurenames] = ExtractSurfaceFeatures(surfaces, windowsize)
%function [features, featurenames] = ExtractSurfaceFeatures(surfaces, windowsize)
%  DECRIPTION
%    This function extracts the 7 features listed below from the given surfaces based on the
%    given window size.
%    Features extracted: 1. Mean
%                        2. Variance
%                        3. Skewness
%                        4. Kurtosis
%                        5. Fifth Moment
%                        6. Area of Crossings
%                        7. Sum of Changes
%                        8. Sum of High Frequencies
%  INPUT
%    surfaces: An array of N clean surface data imported from the file generated by MAEVA.
%    windowsize: Number of samples in each window
%               (It should correspond to a multiple of the acquisition data rate of MAEVA).
%  OUTPUT
%    features : An array of N extracted surface features.
%    featurenames: An array of N surface feature names based on the features above.

    %% Extract the features from the surface data
    surfaceindex = 1;
    for surface = 1 : size(surfaces, 2)
        if (~isempty(surfaces{surface}))
            disp(['Extracting features from data of surface ', num2str(surface)]);
            windowindex = 1;
            for windowstart = 0 : windowsize : (size(surfaces{surface}, 1) - windowsize)
                for axis = 1 : size(surfaces{surface}, 2)
                    [features{surfaceindex}(windowindex, axis, :), featurenames{surfaceindex}(axis, :)] = ...
                        ExtractFeatures(surfaces{surface}(windowstart + (1:windowsize), axis));
                end
                windowindex = windowindex + 1;
            end
            surfaceindex = surfaceindex + 1;
        end
    end
end
