function importedsurfaces = ImportRawSurfaceData(folder)
%function importedsurfaces = ImportRawSurfaceData(folder)
%  DESCRIPTION
%    This function returns a N x 2 matrix of data imported from N files
%    generated by MAEVA (.dat files) and located in the given folder.
%  INPUT
%    folder: The folder name where the data to be imported is located.
%  OUTPUT
%    importedsurfaces: A N x 2 matrix of data imported from N files
%                      acquired by the application MAEVA.

    HEADERLINES = 7;
    DELIMITER   = ',';

    importedsurfaces = {};
    if (isdir(folder))
        oldfolder = cd(folder);
        filelist = dir('*.dat');
        if (size(filelist, 1) > 0)
            for file = 1 : size(filelist, 1)
                disp(['Importing Raw Surface Data File: ', filelist(file).name]);
                filedata = importdata(filelist(file).name, DELIMITER, HEADERLINES);
                importedsurfaces(file, :) = {filedata.textdata, filedata.data};
            end
        end
        cd(oldfolder);
    end
end
